import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Goudy_Bookletter_1911,
  Cinzel,
} from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const goudyBookletter1911 = Goudy_Bookletter_1911({
  weight: "400",
  variable: "--font-goudy-bookletter-1911",
  subsets: ["latin"],
});

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-cinzel-family",
});

export const metadata: Metadata = {
  title: "NewsWebsite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${goudyBookletter1911.variable} ${cinzel.variable} light`}
    >
      <body className="min-h-screen flex flex-col overflow-x-hidden">
        <Header />
        <main className="flex-1 mx-auto w-full max-w-7xl px-1 md:px-8 pt-2 pb-8">
          {children}
        </main>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
